<?php /** @var $this Innobyte_EmagMarketplace_Block_Adminhtml_Sales_Order_View_Invoice_Popup */ ?>
<?php echo $this->getFormInitScripts() ?>
<script type="text/javascript">
    var inno = inno || {};

    inno.emag_marketplace = {
        id: 'emag_invoice_upload_window',
        title: '<?php echo Mage::helper('innobyte_emag_marketplace')->__('eMAG Invoice Upload') ?>',
        url: '<?php echo $this->getUrl('*/sales_invoice_upload/popup', array('_current' => true)) ?>',
        popupWindow: null,
        showPopup: function() {
            if ($('emag_invoice_upload_window') && typeof(Windows) != 'undefined') {
                Windows.focus('emag_invoice_upload_window');
                return;
            }
            this.popupWindow = Dialog.info(null, {
                closable: true,
                resizable: false,
                draggable: true,
                className: 'magento',
                windowClassName: 'popup-window',
                title: this.title,
                top: 50,
                width: 800,
                height: 225,
                zIndex: 1000,
                recenterAuto: false,
                hideEffect: Element.hide,
                showEffect: Element.show,
                id: this.id,
                url: this.url,
                onClose: function (param, el) {
                }
            });
        },
        closePopup: function () {
            Windows.close('emag_invoice_upload_window');
        }
    }


</script>
<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>
<?php echo $this->getFormHtml() ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
<?php echo $this->getFormScripts() ?>
